### PR TITLE
catch unhandled promise rejections

### PR DESCRIPTION
**Pull request by Hades32**
for now, this doesn't change behavior, as we still exit the process, but it fixes error logging. If we don't want to exit the process we can change this later

Change-type: patch

### CODE REVIEW

**Comment by Hades32** [comment]
See https://jel.ly.fish/support-thread-discourse-346979 (which I couldn't link to)

**Review by phil-d-wilson — APPROVED** [review]

**Comment by Hades32** [comment]
@balena-ci republish

**Comment by Hades32** [comment]
@balena-ci retest

**Comment by Bucknalla** [comment]
@Hades32 any reason to not rebase this and merge?

**Comment by Hades32** [comment]
@balena-ci rebase

**Pull request merged**
